### ISSUE TITLE
FR: Live preview disable option

### ISSUE THREAD

**Issue by EternalBlack** [wbrowar/craft-adminbar#16]
This is supposed to be a feature request.

It would be awesome to have an option to disable the admin bar while being in Crafts preview mode.
To elaborate further: When someone is editing an entry inside the CP and clicks on Crafts `Preview` button you get the cp on the left hand side and the actual previewSite on the right hand side. Currently the Admin Bar is still there, which is kind of distracting as in that moment one usually wants to take a look at the design (as well as you know that you are logged in and it's kind of redundant to have the bar there and the admin part on the left side).
Would be awesome to have something like `{{ adminbar({ previewVisibility: false }) }}`

**Comment by wbrowar** [comment]
Thanks for the suggestion, Markus. I'll take a look and see how easy it can be done in the new live preview setup.

**Comment by wbrowar** [comment]
Hey @EternalBlack, this is all set in 3.1.10. It turned out to be a bug introduced in Craft 3.2. Thanks for bringing it to my attention!
